import chromadb
from typing import List, Dict, Any
import src.config as config
from src.embeddings import Embedder
from src.utils import get_logger, time_it

logger = get_logger("VectorDB")

class VectorDB:
    """
    This is the heart of the retrieval system!
    When we chop up the novel into small overlapping chunks, we cannot just save them
    in a regular SQL database because standard databases only search for exact word matches.
    
    ChromaDB is a "Vector Database". It takes the raw text we feed it, gets the math
    from our Embedder, and stores them together. When you ask a question, ChromaDB 
    performs a "similarity search" to find the text chunks whose math most closely matches
    the math of your question.
    """
    
    def __init__(self, collection_name: str):
        # We tell ChromaDB to save its files to the /db directory instead of only keeping it in memory.
        # This way, you don't have to re-process 300 chapters every time you run the script!
        self.client = chromadb.PersistentClient(path=config.DB_DIR)
        
        # We need the embedder ready to convert user questions into math.
        self.embedder = Embedder()
        
        # A ChromaDB "Collection" is like a table in a normal database.
        # By passing the novel name here, we create completely separate, isolated databases
        # for each novel. "became-the-patron" won't mix with "harry-potter".
        
        # ChromaDB requires collection names to be alphanumeric and underscores/hyphens.
        # Let's clean it up just in case.
        safe_name = "".join([c if c.isalnum() else "_" for c in collection_name]).strip("_")
        self.collection_name = safe_name
        
        # Get or create creates the collection if it doesn't exist, or loads it if it does
        self.collection = self.client.get_or_create_collection(name=self.collection_name)
        
    def has_documents(self) -> bool:
        """Returns True if this specific novel's collection has any chunks stored."""
        return self.collection.count() > 0
        
    @time_it
    def store_documents(self, documents: List[Dict[str, Any]]) -> None:
        """
        Takes the raw chunks generated by the DocumentProcessor and inserts them into ChromaDB.
        """
        if not documents:
            logger.warning("No documents provided to store in DB.")
            return

        batch_size = 100 
        total_docs = len(documents)
        logger.info(f"Storing {total_docs} chunks into the database in batches of {batch_size}...")

        # We process in batches to avoid overwhelming memory.
        # This is essentially a sliding window loop going 0 -> 100 -> 200 -> 300.
        for i in range(0, total_docs, batch_size):
            batch = documents[i:i + batch_size]
            
            # We split apart the dictionary into the specific lists ChromaDB expects.
            ids = [doc['id'] for doc in batch]
            texts = [doc['text'] for doc in batch]
            metadatas = [doc['metadata'] for doc in batch]
            
            # Now we use our custom Embedder to get the math for this specific batch.
            embeddings = self.embedder.embed_texts(texts)
            
            # Finally, we push the text, its math, its metadata, and a unique ID into the DB.
            self.collection.upsert(
                ids=ids,
                documents=texts,
                embeddings=embeddings,
                metadatas=metadatas
            )
            logger.info(f"Inserted batch {i // batch_size + 1}/{(total_docs + batch_size - 1) // batch_size}")

        # Adding a quick check to let you track database size!
        logger.info(f"Finished storing. Database now contains {self.collection.count()} chunks.")

    @time_it
    def query(self, question: str, n_results: int = 5) -> Dict:
        """
        Takes the user's plain English question, converts it to math, and finds
        the 'n_results' most mathematically similar chunks in the DB.
        
        The 'results' object returned by Chroma contains the text chunks, the metadata
        (where the chunks came from), and a "distance" score (lower is more accurate).
        """
        logger.info(f"Searching database for query: '{question}'")
        
        # Step 1: Translate user question into a vector using the same model we used to store the text
        query_embedding = self.embedder.embed_query(question)
        
        # Step 2: Ask ChromaDB to find the nearest mathematical neighbours
        # We must pass the query_embedding as a list of lists: [[0.1, 0.4, 0...]]
        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results
        )
        
        # ChromaDB results are complex because it expects to handle multiple questions at once.
        # We only asked one question, so we pull out the first item [0] from its nested lists.
        return {
            "documents": results['documents'][0],
            "metadatas": results['metadatas'][0],
            "distances": results['distances'][0]
        }
